//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subforum
    {
        public Subforum()
        {
            this.Thread = new HashSet<Thread>();
        }
    
        public int id { get; set; }
        public string subforum_name { get; set; }
        public string description { get; set; }
        public int forum_id { get; set; }
    
        public virtual Forum Forum { get; set; }
        public virtual ICollection<Thread> Thread { get; set; }
    }
}
