//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comment = new HashSet<Comment>();
            this.Thread = new HashSet<Thread>();
        }
    
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string battletag { get; set; }
        public int role_id { get; set; }
        public System.DateTime member_since { get; set; }
    
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<Thread> Thread { get; set; }
    }
}
